---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: kamaji-neon-ca-bundle
spec:
  sources:
    - useDefaultCAs: true
  target:
    secret:
      key: ca-certificates.crt
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kamaji-system
