---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kamaji-neon-postgres
  namespace: kamaji-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: kamaji-neon-postgres
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "neondb_owner"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: kamajiNeonPassword
