---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chronoframe-data-v1
  namespace: chronoframe
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ceph-block
